apiVersion: v1
kind: Service
metadata:
  name: {{ include "jaeger-stack.name" . }}-headless
  labels:
    {{- include "jaeger-stack.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "jaeger-stack.selector" . | nindent 4 }}
  ports:
    - {name: otlp-grpc, port: 4317, targetPort: otlp-grpc}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jaeger-stack.name" . }}
  labels:
    {{- include "jaeger-stack.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "jaeger-stack.selector" . | nindent 4 }}
  ports:
    - {name: http, port: 80, targetPort: web, appProtocol: http}
    - {name: otlp-grpc, port: 4317, targetPort: otlp-grpc, appProtocol: grpc}
    - {name: otlp-http, port: 4318, targetPort: otlp-http, appProtocol: http}
    - {name: metrics, port: 8888, targetPort: metrics}
{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "jaeger-stack.name" . }}
  labels:
    {{- include "jaeger-stack.labels" . | nindent 4 }}
    {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "jaeger-stack.selector" . | nindent 6 }}
  endpoints:
    - {port: metrics, interval: 30s}
{{- end }}
