apiVersion: v1
kind: Secret
metadata:
  name: nacos-auth
  labels:
    {{- include "nacos.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ required "auth.token is required" .Values.auth.token | quote }}
  identity-key: {{ required "auth.identityKey is required" .Values.auth.identityKey | quote }}
  identity-value: {{ required "auth.identityValue is required" .Values.auth.identityValue | quote }}
