apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redisinsight.fullname" . }}
  labels:
    {{- include "redisinsight.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ required "basicAuth.password is required" .Values.basicAuth.password | quote }}
  htpasswd: {{ htpasswd (required "basicAuth.username is required" .Values.basicAuth.username) .Values.basicAuth.password | quote }}
  encryption-key: {{ required "encryptionKey is required" .Values.encryptionKey | quote }}
  redis-password: {{ required "connection.redis.password is required" .Values.connection.redis.password | quote }}
