apiVersion: v1
kind: Secret
metadata:
  name: otel-elasticsearch-access
  labels:
    {{- include "otel-elasticsearch.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.auth.username | quote }}
  password: {{ required "auth.password is required" .Values.auth.password | quote }}
