apiVersion: v1
kind: Secret
metadata:
  name: {{ include "etcd-workbench.fullname" . }}
  labels:
    {{- include "etcd-workbench.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ required "basicAuth.username is required" .Values.basicAuth.username | quote }}
  password: {{ required "basicAuth.password is required" .Values.basicAuth.password | quote }}
  encryption-key: {{ required "encryptionKey is required" .Values.encryptionKey | quote }}
  etcd-workbench.conf: |
    [server]
    port = {{ .Values.service.port }}
    etcdExecuteTimeoutMillis = {{ .Values.settings.etcdExecuteTimeoutMillis }}
    dataDir = ./data
    configEncryptKey = {{ .Values.encryptionKey }}
    enableHeartbeat = {{ .Values.settings.enableHeartbeat }}

    [auth]
    enable = true
    user = {{ .Values.basicAuth.username }}:{{ .Values.basicAuth.password }}

    [log]
    level = INFO
    levels = io.netty:INFO,io.grpc:INFO
    file = ./logs
    fileName = etcd-workbench
    fileLimitSize = 10
    printers = std
