{{- if not .Values.admin.password }}{{ fail "admin.password is required" }}{{ end }}
{{- if not .Values.mysql.password }}{{ fail "mysql.password is required" }}{{ end }}
apiVersion: v1
kind: Secret
metadata:
  name: xxl-job-admin
  labels:
    {{- include "xxl-job.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.admin.username | quote }}
  password: {{ .Values.admin.password | quote }}
  mysql-password: {{ .Values.mysql.password | quote }}
