apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "etcd.fullname" . }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
spec:
  minAvailable: {{ div .Values.replicaCount 2 | add 1 }}
  selector:
    matchLabels:
      {{- include "etcd.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
