apiVersion: v1
kind: Secret
metadata:
  name: clickvisual-mysql-auth
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "clickvisual-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: clickvisual
  password: {{ required "secrets.mysqlPassword is required" .Values.secrets.mysqlPassword | quote }}
  database: clickvisual
---
apiVersion: v1
kind: Secret
metadata:
  name: clickvisual-clickhouse-auth
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "clickvisual-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: clickvisual
  password: {{ required "secrets.clickhousePassword is required" .Values.secrets.clickhousePassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: clickvisual-kafka-auth
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "clickvisual-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  cluster-id: {{ required "secrets.kafkaClusterId is required" .Values.secrets.kafkaClusterId | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: clickvisual-stack-access
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "clickvisual-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.clickvisual.username | quote }}
  admin-password: {{ required "secrets.adminPassword is required" .Values.secrets.adminPassword | quote }}
  htpasswd: {{ htpasswd .Values.clickvisual.username .Values.secrets.adminPassword | quote }}
  proxy-token: {{ required "secrets.proxyToken is required" .Values.secrets.proxyToken | quote }}
  clickhouse-password: {{ required "secrets.clickhousePassword is required" .Values.secrets.clickhousePassword | quote }}
