apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-service.fullname" . }}-auth
  labels:
    {{- include "data-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.auth.username | quote }}
  password: {{ required "auth.password is required" .Values.auth.password | quote }}
  database: {{ .Values.auth.database | quote }}
  keyfile: {{ .Values.auth.password | quote }}
