apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-service.fullname" . }}-headless
  labels:
    {{- include "data-service.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "data-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: client
      port: {{ .Values.service.port }}
      targetPort: client
{{- if eq .Values.engine "activemq" }}
    - name: console
      port: 8161
      targetPort: console
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-service.fullname" . }}
  labels:
    {{- include "data-service.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "data-service.selectorLabels" . | nindent 4 }}
{{- if and (eq .Values.engine "mysql") (gt (int .Values.replicaCount) 1) }}
    statefulset.kubernetes.io/pod-name: {{ include "data-service.fullname" . }}-0
{{- end }}
  ports:
    - name: client
      port: {{ .Values.service.port }}
      targetPort: client
{{- if eq .Values.engine "activemq" }}
    - name: console
      port: 8161
      targetPort: console
{{- end }}
