apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bytebase.fullname" . }}
  labels:
    {{- include "bytebase.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-email: {{ required "admin.email is required" .Values.admin.email | quote }}
  admin-password: {{ required "admin.password is required" .Values.admin.password | quote }}
  {{- if .Values.integration.mysql.enabled }}
  mysql-password: {{ required "integration.mysql.password is required" .Values.integration.mysql.password | quote }}
  {{- end }}
