package main

import (
	"bufio"
	"context"
	"crypto/rand"
	"database/sql"
	"encoding/base64"
	"errors"
	"fmt"
	"io"
	"net"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/go-sql-driver/mysql"
	"github.com/redis/go-redis/v9"
	"golang.org/x/term"
)

const (
	datastoreModeLocal    = "local"
	datastoreModeExternal = "external"
)

type datastoreInitConfig struct {
	Mode              string
	MySQLDSN          string
	MySQLPassword     string
	MySQLRootPassword string
	RedisAddress      string
	RedisPassword     string
	RedisDatabase     int
}

func randomSecret(byteCount int, encoding *base64.Encoding) (string, error) {
	value := make([]byte, byteCount)
	if _, err := rand.Read(value); err != nil {
		return "", err
	}
	return encoding.EncodeToString(value), nil
}

func envAssignment(key, value string) string {
	return key + "=" + strconv.Quote(value)
}

func renderInitialEnvironment(passwordHash string, datastore datastoreInitConfig, credentialKey string) []byte {
	lines := []string{
		"# Generated by AWSInfra init. Keep this file private and back it up securely.",
		"# Datastore mode: " + datastore.Mode,
	}
	if datastore.Mode == datastoreModeLocal {
		lines = append(lines,
			envAssignment("OPS_MYSQL_PASSWORD", datastore.MySQLPassword),
			envAssignment("OPS_MYSQL_ROOT_PASSWORD", datastore.MySQLRootPassword),
		)
	}
	lines = append(lines,
		envAssignment("OPS_MYSQL_DSN", datastore.MySQLDSN),
		envAssignment("OPS_DEPLOY_REDIS_ADDRESS", datastore.RedisAddress),
		envAssignment("OPS_DEPLOY_REDIS_DATABASE", strconv.Itoa(datastore.RedisDatabase)),
		envAssignment("OPS_REDIS_PASSWORD", datastore.RedisPassword),
		envAssignment("OPS_DEPLOY_PASSWORD_HASH", passwordHash),
		envAssignment("OPS_DEPLOY_CREDENTIAL_KEY", credentialKey),
		"",
	)
	return []byte(strings.Join(lines, "\n"))
}

func initEnvironmentCLI(configPath, outputPath, requestedMode string, skipDatastoreCheck bool) error {
	if _, err := os.Stat(configPath); err != nil {
		return fmt.Errorf("configuration file is unavailable: %w", err)
	}
	if strings.TrimSpace(outputPath) == "" {
		outputPath = filepath.Join(filepath.Dir(configPath), ".env")
	}
	absoluteOutput, err := filepath.Abs(outputPath)
	if err != nil {
		return fmt.Errorf("resolve init output: %w", err)
	}
	if _, err := os.Stat(absoluteOutput); err == nil {
		return fmt.Errorf("refusing to overwrite existing environment file %s", absoluteOutput)
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("inspect environment file: %w", err)
	}

	passwordHash, err := readNewAdminPasswordHash()
	if err != nil {
		return err
	}
	datastore, err := readDatastoreInitConfig(strings.TrimSpace(strings.ToLower(requestedMode)))
	if err != nil {
		return err
	}
	if datastore.Mode == datastoreModeExternal && !skipDatastoreCheck {
		fmt.Fprintln(os.Stderr, "正在验证 MySQL 与 Redis 连接…")
		if err := checkExternalDatastores(datastore); err != nil {
			return fmt.Errorf("数据存储连接验证失败（确认网络、账号、数据库和白名单，或使用 --skip-datastore-check 仅生成配置）: %w", err)
		}
		fmt.Fprintln(os.Stderr, "MySQL 与 Redis 连接验证通过。")
	}
	credentialKey, err := randomSecret(32, base64.StdEncoding)
	if err != nil {
		return fmt.Errorf("generate credential encryption key: %w", err)
	}

	file, err := os.OpenFile(absoluteOutput, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if errors.Is(err, os.ErrExist) {
		return fmt.Errorf("refusing to overwrite existing environment file %s", absoluteOutput)
	}
	if err != nil {
		return fmt.Errorf("create environment file: %w", err)
	}
	payload := renderInitialEnvironment(passwordHash, datastore, credentialKey)
	if _, err = file.Write(payload); err != nil {
		_ = file.Close()
		_ = os.Remove(absoluteOutput)
		return fmt.Errorf("write environment file: %w", err)
	}
	if err = file.Close(); err != nil {
		_ = os.Remove(absoluteOutput)
		return fmt.Errorf("close environment file: %w", err)
	}
	if err := os.Chmod(absoluteOutput, 0o600); err != nil {
		return fmt.Errorf("secure environment file: %w", err)
	}
	fmt.Printf("初始化完成：%s。请安全备份；OPS_DEPLOY_CREDENTIAL_KEY 丢失后，已保存凭据将无法解密。\n", absoluteOutput)
	if datastore.Mode == datastoreModeLocal {
		fmt.Println("下一步：docker compose up -d --wait mysql redis")
	}
	return nil
}

func readDatastoreInitConfig(mode string) (datastoreInitConfig, error) {
	reader := bufio.NewReader(os.Stdin)
	if mode == "" {
		fmt.Fprintln(os.Stderr, "数据存储模式：")
		fmt.Fprintln(os.Stderr, "  1. 本地 Docker MySQL/Redis（推荐首次体验）")
		fmt.Fprintln(os.Stderr, "  2. 已有 MySQL/Redis")
		value, err := promptLine(reader, "请选择", "1", true)
		if err != nil {
			return datastoreInitConfig{}, err
		}
		mode = value
	}
	switch mode {
	case "1", datastoreModeLocal:
		return newLocalDatastoreConfig()
	case "2", datastoreModeExternal:
		return readExternalDatastoreConfig(reader)
	default:
		return datastoreInitConfig{}, fmt.Errorf("unsupported datastore mode %q; use local or external", mode)
	}
}

func newLocalDatastoreConfig() (datastoreInitConfig, error) {
	mysqlPassword, err := randomSecret(24, base64.RawURLEncoding)
	if err != nil {
		return datastoreInitConfig{}, fmt.Errorf("generate MySQL password: %w", err)
	}
	mysqlRootPassword, err := randomSecret(24, base64.RawURLEncoding)
	if err != nil {
		return datastoreInitConfig{}, fmt.Errorf("generate MySQL root password: %w", err)
	}
	redisPassword, err := randomSecret(24, base64.RawURLEncoding)
	if err != nil {
		return datastoreInitConfig{}, fmt.Errorf("generate Redis password: %w", err)
	}
	return datastoreInitConfig{
		Mode:              datastoreModeLocal,
		MySQLDSN:          formatMySQLDSN("127.0.0.1", 13306, "ops_deploy", "ops", mysqlPassword, "false"),
		MySQLPassword:     mysqlPassword,
		MySQLRootPassword: mysqlRootPassword,
		RedisAddress:      "127.0.0.1:6379",
		RedisPassword:     redisPassword,
		RedisDatabase:     0,
	}, nil
}

func readExternalDatastoreConfig(reader *bufio.Reader) (datastoreInitConfig, error) {
	fmt.Fprintln(os.Stderr, "请填写已有数据存储连接信息；密码只会写入本机权限受限的 .env。")
	mysqlHost, err := promptLine(reader, "MySQL 主机", "127.0.0.1", true)
	if err != nil {
		return datastoreInitConfig{}, err
	}
	if err := validateHost(mysqlHost); err != nil {
		return datastoreInitConfig{}, fmt.Errorf("invalid MySQL host: %w", err)
	}
	mysqlPort, err := promptInteger(reader, "MySQL 端口", 3306, 1, 65535)
	if err != nil {
		return datastoreInitConfig{}, err
	}
	mysqlDatabase, err := promptLine(reader, "MySQL 数据库", "ops_deploy", true)
	if err != nil {
		return datastoreInitConfig{}, err
	}
	if err := validateDatabaseName(mysqlDatabase); err != nil {
		return datastoreInitConfig{}, fmt.Errorf("invalid MySQL database: %w", err)
	}
	mysqlUsername, err := promptLine(reader, "MySQL 用户名", "ops", true)
	if err != nil {
		return datastoreInitConfig{}, err
	}
	if strings.ContainsAny(mysqlUsername, ":@/\\\t\r\n\x00") {
		return datastoreInitConfig{}, errors.New("invalid MySQL username: reserved DSN characters are not supported")
	}
	mysqlPassword, err := promptSecret("MySQL 密码", false)
	if err != nil {
		return datastoreInitConfig{}, err
	}
	mysqlTLS, err := promptLine(reader, "MySQL TLS（false/true/skip-verify/preferred）", "false", true)
	if err != nil {
		return datastoreInitConfig{}, err
	}
	if !map[string]bool{"false": true, "true": true, "skip-verify": true, "preferred": true}[mysqlTLS] {
		return datastoreInitConfig{}, errors.New("MySQL TLS must be false, true, skip-verify, or preferred")
	}

	redisHost, err := promptLine(reader, "Redis 主机", "127.0.0.1", true)
	if err != nil {
		return datastoreInitConfig{}, err
	}
	if err := validateHost(redisHost); err != nil {
		return datastoreInitConfig{}, fmt.Errorf("invalid Redis host: %w", err)
	}
	redisPort, err := promptInteger(reader, "Redis 端口", 6379, 1, 65535)
	if err != nil {
		return datastoreInitConfig{}, err
	}
	redisPassword, err := promptSecret("Redis 密码（无密码可直接回车）", true)
	if err != nil {
		return datastoreInitConfig{}, err
	}
	redisDatabase, err := promptInteger(reader, "Redis Database", 0, 0, 1024)
	if err != nil {
		return datastoreInitConfig{}, err
	}
	return datastoreInitConfig{
		Mode:          datastoreModeExternal,
		MySQLDSN:      formatMySQLDSN(mysqlHost, mysqlPort, mysqlDatabase, mysqlUsername, mysqlPassword, mysqlTLS),
		RedisAddress:  net.JoinHostPort(strings.Trim(strings.TrimSpace(redisHost), "[]"), strconv.Itoa(redisPort)),
		RedisPassword: redisPassword,
		RedisDatabase: redisDatabase,
	}, nil
}

func formatMySQLDSN(host string, port int, database, username, password, tlsMode string) string {
	configuration := mysql.NewConfig()
	configuration.User = username
	configuration.Passwd = password
	configuration.Net = "tcp"
	configuration.Addr = net.JoinHostPort(strings.Trim(strings.TrimSpace(host), "[]"), strconv.Itoa(port))
	configuration.DBName = database
	configuration.ParseTime = true
	configuration.Collation = "utf8mb4_unicode_ci"
	if tlsMode != "" && tlsMode != "false" {
		configuration.TLSConfig = tlsMode
	}
	return configuration.FormatDSN()
}

func promptLine(reader *bufio.Reader, label, defaultValue string, required bool) (string, error) {
	if defaultValue == "" {
		fmt.Fprintf(os.Stderr, "%s: ", label)
	} else {
		fmt.Fprintf(os.Stderr, "%s [%s]: ", label, defaultValue)
	}
	value, err := reader.ReadString('\n')
	if err != nil && !(errors.Is(err, io.EOF) && value != "") {
		return "", err
	}
	value = strings.TrimSpace(value)
	if value == "" {
		value = defaultValue
	}
	if required && value == "" {
		return "", fmt.Errorf("%s cannot be empty", label)
	}
	if strings.ContainsAny(value, "\r\n\x00") {
		return "", fmt.Errorf("%s contains invalid control characters", label)
	}
	return value, nil
}

func promptInteger(reader *bufio.Reader, label string, defaultValue, minimum, maximum int) (int, error) {
	value, err := promptLine(reader, label, strconv.Itoa(defaultValue), true)
	if err != nil {
		return 0, err
	}
	parsed, err := strconv.Atoi(value)
	if err != nil || parsed < minimum || parsed > maximum {
		return 0, fmt.Errorf("%s must be between %d and %d", label, minimum, maximum)
	}
	return parsed, nil
}

func promptSecret(label string, allowEmpty bool) (string, error) {
	if !term.IsTerminal(int(os.Stdin.Fd())) {
		return "", errors.New("an interactive terminal is required")
	}
	fmt.Fprintf(os.Stderr, "%s: ", label)
	value, err := term.ReadPassword(int(os.Stdin.Fd()))
	fmt.Fprintln(os.Stderr)
	if err != nil {
		return "", err
	}
	defer clear(value)
	if !allowEmpty && len(value) == 0 {
		return "", fmt.Errorf("%s cannot be empty", label)
	}
	if strings.ContainsAny(string(value), "\r\n\x00") {
		return "", fmt.Errorf("%s contains invalid control characters", label)
	}
	return string(value), nil
}

func validateHost(value string) error {
	value = strings.Trim(strings.TrimSpace(value), "[]")
	if value == "" || strings.ContainsAny(value, " /\\\t\r\n\x00") {
		return errors.New("host must be a DNS name or IP address without a port")
	}
	return nil
}

func validateDatabaseName(value string) error {
	if value == "" || len(value) > 64 {
		return errors.New("database name must contain 1 to 64 characters")
	}
	for _, character := range value {
		if (character >= 'a' && character <= 'z') || (character >= 'A' && character <= 'Z') ||
			(character >= '0' && character <= '9') || character == '_' || character == '-' || character == '$' {
			continue
		}
		return errors.New("database name may contain only letters, digits, underscore, hyphen, and dollar sign")
	}
	return nil
}

func checkExternalDatastores(configuration datastoreInitConfig) error {
	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()
	database, err := sql.Open("mysql", configuration.MySQLDSN)
	if err != nil {
		return fmt.Errorf("open MySQL: %w", err)
	}
	defer database.Close()
	if err := database.PingContext(ctx); err != nil {
		return fmt.Errorf("connect MySQL: %w", err)
	}
	cache := redis.NewClient(&redis.Options{
		Addr:     configuration.RedisAddress,
		Password: configuration.RedisPassword,
		DB:       configuration.RedisDatabase,
	})
	defer cache.Close()
	if err := cache.Ping(ctx).Err(); err != nil {
		return fmt.Errorf("connect Redis: %w", err)
	}
	return nil
}
