apiVersion: v1
kind: Secret
metadata:
  name: efk-stack-access
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "efk-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: elastic
  elastic-password: {{ required "secrets.elasticPassword is required" .Values.secrets.elasticPassword | quote }}
  kibana-system-password: {{ required "secrets.kibanaSystemPassword is required" .Values.secrets.kibanaSystemPassword | quote }}
  fluentd-username: fluentd_writer
  fluentd-password: {{ required "secrets.fluentdPassword is required" .Values.secrets.fluentdPassword | quote }}
  security-encryption-key: {{ required "secrets.securityEncryptionKey is required" .Values.secrets.securityEncryptionKey | quote }}
  saved-objects-encryption-key: {{ required "secrets.savedObjectsEncryptionKey is required" .Values.secrets.savedObjectsEncryptionKey | quote }}
  reporting-encryption-key: {{ required "secrets.reportingEncryptionKey is required" .Values.secrets.reportingEncryptionKey | quote }}
