image:
  repository: tzfun/etcd-workbench
  tag: "1.1.4@sha256:c58de0e1b96ebdc01856c8ef87d9cd6f2113e4d8acdd32965e5d3c6cdc949b71"
  pullPolicy: IfNotPresent

service:
  port: 8002

basicAuth:
  username: admin
  password: ""

encryptionKey: ""
settings:
  etcdExecuteTimeoutMillis: 5000
  enableHeartbeat: true

persistence:
  enabled: true
  storageClass: gp3
  size: 5Gi
  retainOnDelete: true

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

nodeSelector: {}
tolerations: []
affinity: {}
