package gitlab

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"regexp"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/GZ-Alinx/awsinfra/internal/appconfig"
	"github.com/GZ-Alinx/awsinfra/internal/cicd"
	"gopkg.in/yaml.v3"
)

func TestProjectDeliveryUsesOneEnvironmentScopedRepository(t *testing.T) {
	store := newMemoryStore()
	service := newTestService(t, store)
	server, err := service.SaveServer(context.Background(), "", ServerInput{
		Key: "main", DisplayName: "Main GitLab", BaseURL: "https://gitlab.example.com", AccessToken: "secret-token",
		RootGroup: "ops/delivery", DefaultBranch: "main", Visibility: "private",
	})
	if err != nil || !server.Configured {
		t.Fatalf("SaveServer() = %#v, %v", server, err)
	}
	stored := store.servers["main"]
	if stored.TokenCipher == "" || strings.Contains(stored.TokenCipher, "secret-token") {
		t.Fatal("GitLab token was not encrypted")
	}
	delivery, err := service.SaveDelivery(context.Background(), "game-api", ProjectDelivery{ServerKey: "main", Services: []ServiceSpec{{
		Key: "gateway", DisplayName: "Gateway", Language: "go", SourceRepository: "https://gitlab.example.com/game/gateway.git",
		ImageRepository: "123456789012.dkr.ecr.ap-south-1.amazonaws.com/game-api/gateway",
	}}})
	if err != nil {
		t.Fatal(err)
	}
	if delivery.JenkinsfilesProjectPath != "ops/delivery/game-api-ops-delivery" || delivery.ManifestsProjectPath != delivery.JenkinsfilesProjectPath {
		t.Fatalf("unexpected repository paths: %#v", delivery)
	}
	if len(delivery.Services) != 1 || delivery.Services[0].Namespace != "game-api" || delivery.Services[0].SourceBranch != "main" {
		t.Fatalf("service defaults were not applied: %#v", delivery.Services)
	}
	files := generateDeliveryFiles("game-api", delivery, server)
	assertGeneratedPath(t, files, "delivery", "environments/dev/gateway/manifest.yaml")
	assertGeneratedPath(t, files, "delivery", "environments/dev/dockerfiles/gateway/Dockerfile")
	assertGeneratedPath(t, files, "delivery", "environments/prod/dockerfiles/gateway/Dockerfile")
	if delivery.Services[0].DockerfileSource != "platform" || delivery.Services[0].Dockerfile != "dockerfiles/gateway/Dockerfile" || !strings.Contains(delivery.Services[0].DockerfileContent, "FROM golang:1.24-bookworm") {
		t.Fatalf("managed Dockerfile defaults were not applied: %#v", delivery.Services[0])
	}
	for _, file := range files {
		if strings.HasSuffix(file.Path, "kustomization.yaml") {
			t.Fatalf("obsolete kustomization file was generated: %s", file.Path)
		}
	}
	for _, file := range files {
		if file.Repository == "delivery" && strings.Contains(file.Path, "services/gateway") {
			t.Fatalf("service Jenkinsfile must be generated by a CI/CD job, got %s", file.Path)
		}
	}
	for _, file := range files {
		if strings.Contains(file.Content, "secret-token") {
			t.Fatalf("secret leaked into generated file %s", file.Path)
		}
		if strings.Contains(file.Content, "%!") {
			t.Fatalf("formatting error in generated file %s: %s", file.Path, file.Content)
		}
	}
}

func TestRepositoryMaintainedManifestIsNotOverwritten(t *testing.T) {
	delivery := ProjectDelivery{Services: []ServiceSpec{
		{Key: "gateway", ManifestMode: "repository", DockerfileContent: "FROM scratch\n"},
		{Key: "api", ManifestMode: "platform", DockerfileContent: "FROM scratch\n"},
	}}
	files := generateDeliveryFiles("game-api", delivery, Server{})
	assertGeneratedPath(t, files, "jenkinsfiles", "environments/test/dockerfiles/gateway/Dockerfile")
	assertGeneratedPath(t, files, "jenkinsfiles", "environments/test/dockerfiles/api/Dockerfile")
	assertGeneratedPath(t, files, "manifests", "environments/test/api/manifest.yaml")
	for _, file := range files {
		if file.Repository == "manifests" && strings.Contains(file.Path, "/gateway/") {
			t.Fatalf("repository-maintained manifest was generated: %s", file.Path)
		}
	}
}

func TestProjectDeliveryBindsBusinessSourceGitLabSeparately(t *testing.T) {
	store := newMemoryStore()
	service := newTestService(t, store)
	for _, input := range []ServerInput{
		{Key: "delivery", DisplayName: "Delivery GitLab", BaseURL: "https://delivery.example.com/gitlab", AccessToken: "delivery-token", RootGroup: "ops/delivery", Visibility: "private"},
		{Key: "business", DisplayName: "Business GitLab", BaseURL: "https://business.example.com/gitlab", AccessToken: "business-token", RootGroup: "kbp_game", Visibility: "private"},
	} {
		if _, err := service.SaveServer(context.Background(), "", input); err != nil {
			t.Fatal(err)
		}
	}
	delivery, err := service.SaveDelivery(context.Background(), "game-api", ProjectDelivery{
		ServerKey: "delivery", SourceServerKey: "business", Services: []ServiceSpec{{
			Key: "gateway", Language: "go", SourceRepository: "https://business.example.com/gitlab/kbp_game/game_server/gateway.git", ImageRepository: "registry.example/game/gateway",
		}},
	})
	if err != nil {
		t.Fatal(err)
	}
	if delivery.ServerKey != "delivery" || delivery.SourceServerKey != "business" || delivery.SourceRootGroup != "kbp_game" {
		t.Fatalf("independent GitLab bindings were not saved: %#v", delivery)
	}
	repository, err := store.GetCICDRepository(context.Background(), "game-api", "source-gateway")
	if err != nil || repository.CloneURL != "https://business.example.com/gitlab/kbp_game/game_server/gateway.git" || repository.Purpose != "source" {
		t.Fatalf("source repository registration = %#v, %v", repository, err)
	}
	if _, err := service.SaveDelivery(context.Background(), "game-api", ProjectDelivery{
		ServerKey: "delivery", SourceServerKey: "business", Services: []ServiceSpec{{
			Key: "gateway", Language: "go", SourceRepository: "https://other.example.com/kbp_game/gateway.git", ImageRepository: "registry.example/game/gateway",
		}},
	}); err == nil {
		t.Fatal("cross-server business repository was accepted")
	}
}

func TestProjectDeliveryCanSwitchToEquivalentSourceConnection(t *testing.T) {
	store := newMemoryStore()
	service := newTestService(t, store)
	for _, input := range []ServerInput{
		{Key: "delivery", DisplayName: "Delivery GitLab", BaseURL: "https://delivery.example.com", AccessToken: "delivery-token", RootGroup: "ops", Visibility: "private"},
		{Key: "business-old", DisplayName: "Business GitLab Old", BaseURL: "https://business.example.com", AccessToken: "old-token", RootGroup: "kbp_game", Visibility: "private"},
		{Key: "business-new", DisplayName: "Business GitLab New", BaseURL: "https://business.example.com", AccessToken: "new-token", RootGroup: "kbp_game", Visibility: "private"},
	} {
		if _, err := service.SaveServer(context.Background(), "", input); err != nil {
			t.Fatal(err)
		}
	}
	input := ProjectDelivery{
		ServerKey: "delivery", SourceServerKey: "business-old", Services: []ServiceSpec{{
			Key: "gateway", Language: "go", SourceRepository: "https://business.example.com/kbp_game/game_server/gateway.git", ImageRepository: "registry.example/game/gateway",
		}},
	}
	if _, err := service.SaveDelivery(context.Background(), "game-api", input); err != nil {
		t.Fatal(err)
	}
	input.SourceServerKey = "business-new"
	delivery, err := service.SaveDelivery(context.Background(), "game-api", input)
	if err != nil {
		t.Fatalf("equivalent source connection should be directly reusable: %v", err)
	}
	if delivery.SourceServerKey != "business-new" {
		t.Fatalf("source connection was not updated: %#v", delivery)
	}
}

func TestGitLabServerSupportsMultipleAuthorizedRootGroups(t *testing.T) {
	store := newMemoryStore()
	service := newTestService(t, store)
	server, err := service.SaveServer(context.Background(), "", ServerInput{
		Key: "main", DisplayName: "Main GitLab", BaseURL: "https://gitlab.example.com", AccessToken: "secret-token",
		RootGroups: []string{"ops", "bigdata_group", "OPS"}, Visibility: "private",
	})
	if err != nil {
		t.Fatal(err)
	}
	if server.RootGroup != "ops" || len(server.RootGroups) != 2 || server.RootGroups[1] != "bigdata_group" {
		t.Fatalf("root groups were not normalized: %#v", server)
	}
	delivery, err := service.SaveDelivery(context.Background(), "game-api", ProjectDelivery{ServerKey: "main", RootGroup: "bigdata_group"})
	if err != nil {
		t.Fatal(err)
	}
	if delivery.RootGroup != "bigdata_group" || delivery.JenkinsfilesProjectPath != "bigdata_group/game-api-ops-delivery" || delivery.ManifestsProjectPath != delivery.JenkinsfilesProjectPath {
		t.Fatalf("selected root group was not used: %#v", delivery)
	}
	// Subsequent service updates may omit the root group; the project binding
	// must remain stable instead of falling back to the server default.
	delivery, err = service.SaveDelivery(context.Background(), "game-api", ProjectDelivery{ServerKey: "main"})
	if err != nil || delivery.RootGroup != "bigdata_group" {
		t.Fatalf("selected root group was not preserved: %#v, %v", delivery, err)
	}
	if _, err := service.SaveDelivery(context.Background(), "other-api", ProjectDelivery{ServerKey: "main", RootGroup: "unauthorized"}); err == nil {
		t.Fatal("unauthorized root group was accepted")
	}
}

func TestBoundGitLabRootGroupCannotBeRemoved(t *testing.T) {
	store := newMemoryStore()
	service := newTestService(t, store)
	if _, err := service.SaveServer(context.Background(), "", ServerInput{
		Key: "main", DisplayName: "Main GitLab", BaseURL: "https://gitlab.example.com", AccessToken: "secret-token",
		RootGroups: []string{"ops", "bigdata_group"}, Visibility: "private",
	}); err != nil {
		t.Fatal(err)
	}
	if _, err := service.SaveDelivery(context.Background(), "game-api", ProjectDelivery{ServerKey: "main", RootGroup: "bigdata_group"}); err != nil {
		t.Fatal(err)
	}
	if _, err := service.SaveServer(context.Background(), "main", ServerInput{
		Key: "main", DisplayName: "Main GitLab", BaseURL: "https://gitlab.example.com", RootGroups: []string{"ops"}, Visibility: "private",
	}); err == nil || !strings.Contains(err.Error(), "bigdata_group") {
		t.Fatalf("bound root group removal was not rejected: %v", err)
	}
}

func TestValidateRepositoryServerSupportsGitLabSubpath(t *testing.T) {
	valid := []string{
		"https://gitlab.example.com/gitlab/kbp_game/gateway.git",
		"https://gitlab.example.com/gitlab/kbp_game/game_server/gateway.git",
	}
	for _, repository := range valid {
		if err := validateRepositoryServer(repository, "https://gitlab.example.com/gitlab", "kbp_game"); err != nil {
			t.Fatalf("valid repository %s was rejected: %v", repository, err)
		}
	}
	invalid := []string{
		"https://gitlab.example.com/kbp_game/gateway.git",
		"https://gitlab.example.com/gitlab/other/gateway.git",
		"https://other.example.com/gitlab/kbp_game/gateway.git",
	}
	for _, repository := range invalid {
		if err := validateRepositoryServer(repository, "https://gitlab.example.com/gitlab", "kbp_game"); err == nil {
			t.Fatalf("invalid repository %s was accepted", repository)
		}
	}
}

func TestSourceCredentialUsesProjectReadOnlyDeployToken(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/kbp_game/gateway.git/info/refs" {
			username, password, ok := r.BasicAuth()
			if !ok || username != "deploy-user" || password != "deploy-secret" || r.URL.Query().Get("service") != "git-upload-pack" {
				http.Error(w, "unauthorized", http.StatusUnauthorized)
				return
			}
			w.Header().Set("Content-Type", "application/x-git-upload-pack-advertisement")
			_, _ = io.WriteString(w, "001e# service=git-upload-pack\n0000")
			return
		}
		if r.Header.Get("PRIVATE-TOKEN") != "api-token" {
			http.Error(w, `{"message":"unauthorized"}`, http.StatusUnauthorized)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		switch {
		case r.Method == http.MethodGet && r.URL.Path == "/api/v4/groups/kbp_game":
			_ = json.NewEncoder(w).Encode(gitLabGroup{ID: 9, FullPath: "kbp_game"})
		case r.Method == http.MethodGet && r.URL.Path == "/api/v4/groups/9/deploy_tokens":
			_, _ = io.WriteString(w, `[]`)
		case r.Method == http.MethodPost && r.URL.Path == "/api/v4/groups/9/deploy_tokens":
			w.WriteHeader(http.StatusCreated)
			_ = json.NewEncoder(w).Encode(gitLabDeployToken{ID: 71, Name: "ops-deploy-game-api-jenkins-test-source-read", Username: "deploy-user", Token: "deploy-secret", Scopes: []string{"read_repository"}})
		default:
			http.NotFound(w, r)
		}
	}))
	defer server.Close()
	store := newMemoryStore()
	service := newTestService(t, store)
	_, err := service.SaveServer(context.Background(), "", ServerInput{Key: "business", DisplayName: "Business GitLab", BaseURL: server.URL, AccessToken: "api-token", RootGroup: "kbp_game", Visibility: "private", AllowInsecureHTTP: true})
	if err != nil {
		t.Fatal(err)
	}
	_, err = service.SaveDelivery(context.Background(), "game-api", ProjectDelivery{ServerKey: "business", SourceServerKey: "business", Services: []ServiceSpec{{Key: "gateway", Language: "go", SourceRepository: server.URL + "/kbp_game/gateway.git", ImageRepository: "registry.example/game/gateway"}}})
	if err != nil {
		t.Fatal(err)
	}
	syncer := &fakeCredentialSyncer{items: map[string]cicd.Credential{}}
	credential, err := service.SyncSourceCredential(context.Background(), "game-api", "jenkins-test", []string{"gateway"}, syncer)
	if err != nil {
		t.Fatal(err)
	}
	if credential.ExternalID != "ops-game-api-source-read" || credential.ConnectionKey != "jenkins-test" || credential.SyncStatus != "ready" {
		t.Fatalf("unexpected synchronized credential: %#v", credential)
	}
	if syncer.saved.Kind != "gitlab_token" || syncer.saved.Username != "deploy-user" || syncer.saved.Password != "deploy-secret" || !strings.Contains(syncer.saved.Description, "仅 read_repository") {
		t.Fatalf("Jenkins received an unexpected credential payload: %#v", syncer.saved)
	}
	if syncer.saved.Password == "api-token" {
		t.Fatal("high-privilege GitLab API token was copied to Jenkins")
	}
}

func TestSourceCredentialFallsBackWhenDeployTokenScopeIsInsufficient(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/kbp_game/gateway.git/info/refs" {
			username, password, ok := r.BasicAuth()
			if !ok || username != "oauth2" || password != "source-read-token" || r.URL.Query().Get("service") != "git-upload-pack" {
				http.Error(w, "unauthorized", http.StatusUnauthorized)
				return
			}
			w.Header().Set("Content-Type", "application/x-git-upload-pack-advertisement")
			_, _ = io.WriteString(w, "001e# service=git-upload-pack\n0000")
			return
		}
		if r.Header.Get("PRIVATE-TOKEN") != "source-read-token" {
			http.Error(w, `{"message":"unauthorized"}`, http.StatusUnauthorized)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		switch {
		case r.Method == http.MethodGet && r.URL.Path == "/api/v4/groups/kbp_game":
			_ = json.NewEncoder(w).Encode(gitLabGroup{ID: 9, FullPath: "kbp_game"})
		case r.Method == http.MethodGet && r.URL.Path == "/api/v4/groups/9/deploy_tokens":
			_, _ = io.WriteString(w, `[]`)
		case r.Method == http.MethodPost && r.URL.Path == "/api/v4/groups/9/deploy_tokens":
			w.WriteHeader(http.StatusForbidden)
			_, _ = io.WriteString(w, `{"error":"insufficient_scope","error_description":"The request requires higher privileges than provided by the access token.","scope":"api read_api"}`)
		default:
			http.NotFound(w, r)
		}
	}))
	defer server.Close()

	store := newMemoryStore()
	service := newTestService(t, store)
	if _, err := service.SaveServer(context.Background(), "", ServerInput{Key: "business", DisplayName: "Business GitLab", BaseURL: server.URL, AccessToken: "source-read-token", RootGroup: "kbp_game", Visibility: "private", AllowInsecureHTTP: true}); err != nil {
		t.Fatal(err)
	}
	if _, err := service.SaveDelivery(context.Background(), "game-api", ProjectDelivery{ServerKey: "business", SourceServerKey: "business", Services: []ServiceSpec{{Key: "gateway", Language: "go", SourceRepository: server.URL + "/kbp_game/gateway.git", ImageRepository: "registry.example/game/gateway"}}}); err != nil {
		t.Fatal(err)
	}
	syncer := &fakeCredentialSyncer{items: map[string]cicd.Credential{}}
	credential, err := service.SyncSourceCredential(context.Background(), "game-api", "jenkins-test", []string{"gateway"}, syncer)
	if err != nil {
		t.Fatal(err)
	}
	if credential.SyncStatus != "ready" || credential.ExternalID != "ops-game-api-source-read" {
		t.Fatalf("compatibility credential was not synchronized: %#v", credential)
	}
	if syncer.saved.Username != "oauth2" || syncer.saved.Password != "source-read-token" || !strings.Contains(syncer.saved.Description, "兼容模式") {
		t.Fatalf("unexpected compatibility credential: %#v", syncer.saved)
	}
}

func TestSourceRepositoryCatalogAggregatesAuthorizedRootGroups(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Header.Get("PRIVATE-TOKEN") != "api-token" {
			http.Error(w, `{"message":"unauthorized"}`, http.StatusUnauthorized)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		switch {
		case r.URL.Path == "/api/v4/groups/ops":
			_ = json.NewEncoder(w).Encode(gitLabGroup{ID: 1, FullPath: "ops"})
		case r.URL.Path == "/api/v4/groups/bigdata_group":
			_ = json.NewEncoder(w).Encode(gitLabGroup{ID: 2, FullPath: "bigdata_group"})
		case r.URL.Path == "/api/v4/groups/1/projects":
			_ = json.NewEncoder(w).Encode([]gitLabProject{{ID: 101, Name: "Pipeline", PathWithNamespace: "ops/pipeline", HTTPURLToRepo: "http://" + r.Host + "/ops/pipeline.git", DefaultBranch: "main"}})
		case r.URL.Path == "/api/v4/groups/2/projects":
			_ = json.NewEncoder(w).Encode([]gitLabProject{{ID: 202, Name: "Analytics", PathWithNamespace: "bigdata_group/analytics", HTTPURLToRepo: "http://" + r.Host + "/bigdata_group/analytics.git", DefaultBranch: "develop"}})
		case r.URL.Path == "/api/v4/projects/202/repository/branches":
			_ = json.NewEncoder(w).Encode([]gitLabBranch{{Name: "develop", Default: true}})
		case r.URL.Path == "/api/v4/projects/202/repository/files/Dockerfile" && r.URL.Query().Get("ref") == "develop":
			content := "FROM eclipse-temurin:21-jre\nWORKDIR /srv/analytics\nENTRYPOINT [\"java\", \"-jar\", \"analytics.jar\"]\n"
			_ = json.NewEncoder(w).Encode(map[string]any{"encoding": "base64", "content": base64.StdEncoding.EncodeToString([]byte(content))})
		default:
			http.Error(w, `{"message":"not found"}`, http.StatusNotFound)
		}
	}))
	defer server.Close()

	store := newMemoryStore()
	service := newTestService(t, store)
	_, err := service.SaveServer(context.Background(), "", ServerInput{Key: "business", DisplayName: "Business GitLab", BaseURL: server.URL, AccessToken: "api-token", RootGroups: []string{"ops", "bigdata_group"}, Visibility: "private", AllowInsecureHTTP: true})
	if err != nil {
		t.Fatal(err)
	}
	_, err = service.SaveDelivery(context.Background(), "game-api", ProjectDelivery{ServerKey: "business", SourceServerKey: "business", Services: []ServiceSpec{{Key: "analytics", Language: "go", SourceRepository: server.URL + "/bigdata_group/analytics.git", SourceBranch: "develop", ImageRepository: "registry.example/game/analytics"}}})
	if err != nil {
		t.Fatalf("second authorized root was rejected by SaveDelivery: %v", err)
	}
	repositories, err := service.ListSourceRepositories(context.Background(), "game-api", "")
	if err != nil {
		t.Fatal(err)
	}
	if len(repositories) != 2 || repositories[0].RootGroup != "bigdata_group" || repositories[1].RootGroup != "ops" {
		t.Fatalf("authorized roots were not aggregated: %#v", repositories)
	}
	branches, err := service.ListSourceRepositoryBranches(context.Background(), "game-api", 202)
	if err != nil || len(branches) != 1 || branches[0].Name != "develop" {
		t.Fatalf("repository in second root could not load branches: %#v, %v", branches, err)
	}
	file, err := service.CheckSourceRepositoryFile(context.Background(), "game-api", 202, "develop", "Dockerfile")
	if err != nil || !file.Exists || file.Path != "Dockerfile" {
		t.Fatalf("existing source Dockerfile was not detected: %#v, %v", file, err)
	}
	missing, err := service.CheckSourceRepositoryFile(context.Background(), "game-api", 202, "develop", "deploy/Dockerfile")
	if err != nil || missing.Exists || missing.Path != "deploy/Dockerfile" {
		t.Fatalf("missing source Dockerfile returned an unexpected result: %#v, %v", missing, err)
	}
	if _, err = service.CheckSourceRepositoryFile(context.Background(), "game-api", 202, "develop", "../Dockerfile"); !errors.Is(err, ErrInvalid) {
		t.Fatalf("unsafe source Dockerfile path was accepted: %v", err)
	}
	_, err = service.SaveServer(context.Background(), "business", ServerInput{Key: "business", DisplayName: "Business GitLab", BaseURL: server.URL, RootGroups: []string{"ops"}, Visibility: "private", AllowInsecureHTTP: true})
	if !errors.Is(err, ErrConflict) {
		t.Fatalf("authorized root used by a source repository was removable: %v", err)
	}
}

func TestSourceCredentialIdentifiersAreRootScoped(t *testing.T) {
	primary := sourceCredentialExternalIDForRoot("game-api", "ops", "ops")
	secondary := sourceCredentialExternalIDForRoot("game-api", "bigdata_group", "ops")
	if primary != "ops-game-api-source-read" || secondary == primary || !strings.HasPrefix(secondary, primary+"-") {
		t.Fatalf("unexpected root-scoped credential identifiers: primary=%q secondary=%q", primary, secondary)
	}
	if sourceCredentialKeyForRoot("jenkins-test", "ops", "ops") == sourceCredentialKeyForRoot("jenkins-test", "bigdata_group", "ops") {
		t.Fatal("different authorized roots reused one Jenkins credential key")
	}
}

func TestGitHTTPAccessRequiresSmartProtocolAdvertisement(t *testing.T) {
	tests := []struct {
		name        string
		status      int
		contentType string
		body        string
		want        bool
	}{
		{name: "smart http", status: http.StatusOK, contentType: "application/x-git-upload-pack-advertisement", body: "001e# service=git-upload-pack\n0000", want: true},
		{name: "login html", status: http.StatusOK, contentType: "text/html; charset=utf-8", body: "<html>sign in</html>"},
		{name: "plain proxy page", status: http.StatusOK, contentType: "text/plain", body: "proxy ok"},
		{name: "unauthorized", status: http.StatusUnauthorized, contentType: "application/x-git-upload-pack-advertisement", body: "001e# service=git-upload-pack\n0000"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, request *http.Request) {
				if request.URL.Path != "/group/repo.git/info/refs" || request.URL.Query().Get("service") != "git-upload-pack" {
					http.NotFound(w, request)
					return
				}
				w.Header().Set("Content-Type", test.contentType)
				w.WriteHeader(test.status)
				_, _ = io.WriteString(w, test.body)
			}))
			defer server.Close()
			client, err := newGitLabClient(server.URL, "api-token")
			if err != nil {
				t.Fatal(err)
			}
			if got := client.gitHTTPAccess(context.Background(), server.URL+"/group/repo.git", "user", "token"); got != test.want {
				t.Fatalf("gitHTTPAccess() = %t, want %t", got, test.want)
			}
		})
	}
}

func TestGeneratedJobUsesModularPipelineAndPerServiceDockerfiles(t *testing.T) {
	job := cicd.Job{Key: "game-release", ProjectKey: "game", DisplayName: "Game Release", ServiceKeys: []string{"gateway", "admin"}, ExecutionMode: "parallel", FailurePolicy: "continue", Parameters: map[string]string{"JENKINS_AGENT_LABEL": "docker-builder", "AWS_PROFILE": "game-test", "DEPLOY_ENV": "test", "MANIFEST_CREDENTIAL_ID": "ops-game-gitlab-read"}}
	services := []ServiceSpec{
		{Key: "gateway", Language: "go", RuntimeVersion: "1.24", SourceRepository: "https://git.example/game/gateway.git", SourceBranch: "main", SourceCredentialID: "gitlab-game", BuildContext: ".", Dockerfile: "Dockerfile", DockerTarget: "runtime-gateway", ImageRepository: "123456789012.dkr.ecr.ap-south-1.amazonaws.com/game/gateway", Namespace: "game-test", EtcdPasswordCredentialID: "game-etcd-password"},
		{Key: "admin", Language: "node", RuntimeVersion: "20", SourceRepository: "https://git.example/game/admin.git", SourceBranch: "main", BuildContext: ".", Dockerfile: "Dockerfile", ImageRepository: "123456789012.dkr.ecr.ap-south-1.amazonaws.com/game/admin", Namespace: "game-test"},
	}
	files := generateJobFiles(job, services, "https://git.example/game/manifests.git", "main")
	for _, path := range []string{
		"jobs/game-release/Jenkinsfile",
		"jobs/game-release/services.groovy",
		pipelineLibraryPath,
		kanikoBuildScriptPath,
		dockerBuildScriptPath,
		deployScriptPath,
		"environments/test/dockerfiles/gateway/Dockerfile",
		"environments/test/dockerfiles/admin/Dockerfile",
	} {
		assertGeneratedPath(t, files, "jenkinsfiles", path)
	}
	if len(files) != 8 {
		t.Fatalf("modular Job should generate entrypoint, catalog, runtime modules and per-service Dockerfiles, got %#v", files)
	}
	jenkinsfile := generatedFileContent(t, files, "jenkinsfiles", "jobs/game-release/Jenkinsfile")
	catalog := generatedFileContent(t, files, "jenkinsfiles", "jobs/game-release/services.groovy")
	library := generatedFileContent(t, files, "jenkinsfiles", pipelineLibraryPath)
	kanikoScript := generatedFileContent(t, files, "jenkinsfiles", kanikoBuildScriptPath)
	dockerScript := generatedFileContent(t, files, "jenkinsfiles", dockerBuildScriptPath)
	deployScript := generatedFileContent(t, files, "jenkinsfiles", deployScriptPath)
	all := strings.Join([]string{jenkinsfile, catalog, library, kanikoScript, dockerScript, deployScript}, "\n")

	if !strings.HasPrefix(jenkinsfile, "/*\n * Game Release") || regexp.MustCompile(`@@[A-Z][A-Z0-9_]*@@`).MatchString(all) || strings.Contains(all, "%!") {
		t.Fatalf("generated Jenkinsfile has an invalid header or unresolved template marker:\n%s", jenkinsfile)
	}
	for _, expected := range []string{"Pipeline Schema " + pipelineSchemaVersion, "这个 Jenkinsfile 只负责流程编排", "配置位置：", "label 'docker-builder'", "TARGET_SERVICES", "params.GIT_BRANCH", "script.checkout(pipelineScm)", "loadPipelineDefinition", ".services()", "DEPLOY_ENV = 'test'", "MANIFEST_CREDENTIAL_ID = 'ops-game-gitlab-read'"} {
		if !strings.Contains(jenkinsfile, expected) {
			t.Fatalf("generated Jenkinsfile entrypoint missing %q", expected)
		}
	}
	for _, expected := range []string{"当前 Job 的服务配置", "源码 → 构建 → 镜像 → 部署", "'gateway': [", "'admin': [", "target: 'runtime-gateway'", "game-etcd-password", "credentialId: 'gitlab-game'", "source: [", "build: [", "image: [", "deploy: ["} {
		if !strings.Contains(catalog, expected) {
			t.Fatalf("generated service catalog missing %q", expected)
		}
	}
	for _, expected := range []string{"公共流水线运行模块", "validateServiceConfig", "配置不完整，缺少字段", "1. 源码检出", "2. 镜像构建与推送", "3. Kubernetes 发布", "4. 构建通知", "def checkoutSource(", "def buildAndPushImage(", "def deployService(", "def notifyBuild(", "缺少 {{IMAGE}} 占位符"} {
		if !strings.Contains(library, expected) {
			t.Fatalf("generated pipeline module missing %q", expected)
		}
	}
	if strings.Contains(jenkinsfile, "/kaniko/executor") || strings.Contains(jenkinsfile, "kubectl apply") || strings.Contains(jenkinsfile, "sourceRepository:") {
		t.Fatal("Jenkinsfile entrypoint still embeds build, deploy or service configuration details")
	}
	if login, build := strings.Index(dockerScript, "aws ecr get-login-password"), strings.Index(dockerScript, "DOCKER_BUILDKIT=1 docker build"); login < 0 || build < 0 || login > build {
		t.Fatal("ECR login must happen before docker build so private base images can be pulled")
	}
	for _, forbidden := range []string{"params.IMAGE_TAG", "params.DEPLOY_ENV", "params.MANIFEST_CREDENTIAL_ID"} {
		if strings.Contains(jenkinsfile, forbidden) {
			t.Fatalf("generated Jenkinsfile still exposes internal build parameter %q", forbidden)
		}
	}
	if !strings.Contains(kanikoScript, `if [ -n "${OPS_DOCKER_TARGET:-}" ]`) || !strings.Contains(dockerScript, `if [[ -n "${OPS_DOCKER_TARGET:-}" ]]`) {
		t.Fatal("generated build scripts do not tolerate an empty optional Docker target in strict shell mode")
	}
	for _, expected := range []string{
		`kubectl create --dry-run=client -f "$OPS_RENDERED_MANIFEST" -o name`,
		`kubectl apply --dry-run=server -f "$OPS_RENDERED_MANIFEST"`,
		`kubectl rollout status "deployment/$workload"`,
		`--to-revision="$revision"`,
		`actual_images=$(kubectl get deployment "$workload"`,
	} {
		if !strings.Contains(deployScript, expected) {
			t.Fatalf("generated deploy module is missing %q", expected)
		}
	}
	for _, removed := range []string{"stage('环境预检')", "Build & Package", "config.buildCommand", "go test ./...", "go mod vendor", "EXECUTION_MODE", "FAILURE_POLICY", ".ops-successful-services", "parallel tasks", "OPS_DOCKERFILE_SOURCE=", "OPS_DOCKERFILE="} {
		if strings.Contains(all, removed) {
			t.Fatalf("generated pipeline still contains legacy build/preflight logic %q", removed)
		}
	}
	if strings.Contains(all, "LARK_WEBHOOK = 'http") || strings.Contains(all, "Pass: ") {
		t.Fatal("generated pipeline contains a hard-coded secret")
	}
}

func TestGeneratedJobUsesSelectedManifestRepository(t *testing.T) {
	job := cicd.Job{Key: "release", ServiceKeys: []string{"api"}, JenkinsfileMode: "generated", JenkinsfileCredential: "git-read", ManifestCredential: "git-read", ManifestRepo: "https://relay.example/git/manifests.git", ManifestBranch: "release"}
	services := []ServiceSpec{{Key: "api", Language: "go", SourceRepository: "https://git.example/api.git", SourceBranch: "main", ImageRepository: "123456789012.dkr.ecr.ap-south-1.amazonaws.com/api", Namespace: "test"}}
	files := generateJobFiles(job, services, job.ManifestRepo, job.ManifestBranch)
	jenkinsfile := generatedFileContent(t, files, "jenkinsfiles", "jobs/release/Jenkinsfile")
	if !strings.Contains(jenkinsfile, "MANIFEST_REPOSITORY = 'https://relay.example/git/manifests.git'") || !strings.Contains(jenkinsfile, "MANIFEST_BRANCH = 'release'") {
		t.Fatalf("generated Jenkinsfile ignored selected manifest repository:\n%s", jenkinsfile)
	}
}

func TestSourceRepositoryDockerfileIsUsedWithoutManagedCopy(t *testing.T) {
	store := newMemoryStore()
	service := newTestService(t, store)
	if _, err := service.SaveServer(context.Background(), "", ServerInput{Key: "main", DisplayName: "GitLab", BaseURL: "https://gitlab.example.com", AccessToken: "token", RootGroup: "ops", Visibility: "private"}); err != nil {
		t.Fatal(err)
	}
	delivery, err := service.SaveDelivery(context.Background(), "hichat", ProjectDelivery{ServerKey: "main", Services: []ServiceSpec{{
		Key: "hichat", Language: "java", SourceRepository: "https://gitlab.example.com/bigdata/hichat.git",
		DockerfileSource: "source", Dockerfile: "Dockerfile", DockerfileContent: "FROM scratch\n",
		BuildContext: ".", ImageRepository: "123456789012.dkr.ecr.ap-south-1.amazonaws.com/hichat", Namespace: "test-hichat",
	}}})
	if err != nil {
		t.Fatal(err)
	}
	actual := delivery.Services[0]
	if actual.DockerfileSource != "source" || actual.Dockerfile != "Dockerfile" || actual.DockerfileContent != "" {
		t.Fatalf("source Dockerfile settings were not normalized safely: %#v", actual)
	}
	for _, file := range generateDeliveryFiles("hichat", delivery, Server{}) {
		if file.Repository == "jenkinsfiles" && strings.Contains(file.Path, "dockerfiles/hichat/Dockerfile") {
			t.Fatal("source-repository Dockerfile was duplicated into the Jenkinsfile repository")
		}
	}
	job := cicd.Job{Key: "hichat-release", ServiceKeys: []string{"hichat"}, Parameters: map[string]string{"DEPLOY_ENV": "test"}}
	files := generateJobFiles(job, delivery.Services, "https://gitlab.example.com/ops/hichat-manifests.git", "main")
	if len(files) != 6 {
		t.Fatalf("source Dockerfile Job should generate runtime modules without a managed Dockerfile copy, got %#v", files)
	}
	catalog := generatedFileContent(t, files, "jenkinsfiles", "jobs/hichat-release/services.groovy")
	library := generatedFileContent(t, files, "jenkinsfiles", pipelineLibraryPath)
	buildScripts := generatedFileContent(t, files, "jenkinsfiles", dockerBuildScriptPath) +
		generatedFileContent(t, files, "jenkinsfiles", kanikoBuildScriptPath)
	for _, expected := range []string{"dockerfileSource: 'source'", `.ops-work/${serviceKey}/${config.build.dockerfile}`} {
		if !strings.Contains(catalog+library, expected) {
			t.Fatalf("source Dockerfile modules missing %q", expected)
		}
	}
	for _, expected := range []string{`--file "$OPS_DOCKERFILE_PATH"`, `--dockerfile "$OPS_DOCKERFILE_PATH"`} {
		if !strings.Contains(buildScripts, expected) {
			t.Fatalf("source Dockerfile build scripts missing %q", expected)
		}
	}
}

func TestSourceRepositoryDockerfileRejectsTraversal(t *testing.T) {
	store := newMemoryStore()
	service := newTestService(t, store)
	if _, err := service.SaveServer(context.Background(), "", ServerInput{Key: "main", DisplayName: "GitLab", BaseURL: "https://gitlab.example.com", AccessToken: "token", RootGroup: "ops", Visibility: "private"}); err != nil {
		t.Fatal(err)
	}
	_, err := service.SaveDelivery(context.Background(), "hichat", ProjectDelivery{ServerKey: "main", Services: []ServiceSpec{{
		Key: "hichat", Language: "java", SourceRepository: "https://gitlab.example.com/bigdata/hichat.git",
		DockerfileSource: "source", Dockerfile: "../Dockerfile", ImageRepository: "registry.example/hichat",
	}}})
	if err == nil {
		t.Fatal("source Dockerfile path traversal was accepted")
	}
}

func TestGeneratedJobSupportsKubernetesAgentAndKaniko(t *testing.T) {
	job := cicd.Job{Key: "go-smoke", DisplayName: "Go Smoke", ServiceKeys: []string{"go-smoke"}, ExecutionMode: "serial", FailurePolicy: "stop", Parameters: map[string]string{"JENKINS_AGENT_MODE": "kubernetes", "JENKINS_KUBERNETES_SERVICE_ACCOUNT": "jenkins-go-smoke"}}
	services := []ServiceSpec{{Key: "go-smoke", Language: "go", RuntimeVersion: "1.24", SourceRepository: "https://git.example/ops/go-smoke.git", SourceBranch: "main", SourceCredentialID: "ops-kbp-gitlab", BuildCommand: "go test ./...", BuildContext: ".", Dockerfile: "Dockerfile", ImageRepository: "123456789012.dkr.ecr.ap-south-1.amazonaws.com/kbp/go-smoke", Namespace: "kbp-game"}}
	files := generateJobFiles(job, services, "https://git.example/ops/kbp-deploy-manifests.git", "main")
	jenkinsfile := generatedFileContent(t, files, "jenkinsfiles", "jobs/go-smoke/Jenkinsfile")
	all := jenkinsfile + generatedFileContent(t, files, "jenkinsfiles", pipelineLibraryPath) +
		generatedFileContent(t, files, "jenkinsfiles", kanikoBuildScriptPath)
	for _, expected := range []string{"serviceAccountName: jenkins-go-smoke", "gcr.io/kaniko-project/executor:v1.23.2-debug", "alpine/kubectl:1.34.0", "/kaniko/executor", `--build-arg "SOURCE_GIT_TOKEN=${SOURCE_GIT_TOKEN:-}"`, "container('kubectl')", "OPS_AGENT_MODE = 'kubernetes'"} {
		if !strings.Contains(all, expected) {
			t.Fatalf("Kubernetes pipeline files missing %q", expected)
		}
	}
	if strings.Contains(all, "builder-go-smoke") || strings.Contains(all, "go test ./...") {
		t.Fatal("Kubernetes Jenkinsfile should delegate compilation and tests to the Dockerfile")
	}
	if strings.Contains(jenkinsfile, "label 'master'") {
		t.Fatal("Kubernetes Jenkinsfile should not depend on a fixed Jenkins node")
	}
}

func TestGeneratedBackendAndFrontendManifestsMatchRuntimeShape(t *testing.T) {
	store := newMemoryStore()
	service := newTestService(t, store)
	_, err := service.SaveServer(context.Background(), "", ServerInput{Key: "main", DisplayName: "GitLab", BaseURL: "https://gitlab.example.com", AccessToken: "token", RootGroup: "ops", Visibility: "private"})
	if err != nil {
		t.Fatal(err)
	}
	delivery, err := service.SaveDelivery(context.Background(), "social-dev", ProjectDelivery{ServerKey: "main", Services: []ServiceSpec{
		{
			Key: "come-app-community-api", DisplayName: "Community API", WorkloadType: "backend", Language: "go", SourceRepository: "https://gitlab.example.com/social/community-api.git", ImageRepository: "123456789012.dkr.ecr.ap-south-1.amazonaws.com/social/community-api", Namespace: "social-dev", WorkloadClass: "application", ContainerPort: 11002,
			ImagePullSecrets: []string{"acr-social-acr-vpc"}, EnvironmentVariables: map[string]string{"SPRING_PROFILES_ACTIVE": "test"}, SecretEnvironmentVariables: map[string]SecretKeyReference{"SPRING_DATASOURCE_PASSWORD": {SecretName: "mysql-auth", SecretKey: "password"}}, EtcdConfigEnabled: true, EtcdHosts: []string{"etcd.social-dev.svc.cluster.local:2379"}, EtcdConfigKey: "/config-center/come-app-community-api", EtcdUsername: "admin", EtcdPasswordCredentialID: "social-etcd-password", EtcdConfigFile: "community.yaml", EtcdMountPath: "/app/apps/api/etc/community.yaml",
		},
		{Key: "community-admin", DisplayName: "Community Admin", WorkloadType: "frontend", Language: "node", SourceRepository: "https://gitlab.example.com/social/community-admin.git", ImageRepository: "123456789012.dkr.ecr.ap-south-1.amazonaws.com/social/community-admin", Namespace: "social-dev", ContainerPort: 8080, ImagePullSecrets: []string{"acr-social-acr-vpc"}},
	}})
	if err != nil {
		t.Fatal(err)
	}

	backend := renderManifest("social-dev", "dev", delivery.Services[0])
	frontend := renderManifest("social-dev", "dev", delivery.Services[1])
	for _, expected := range []string{"kind: Secret", "name: come-app-community-api-etcd", "namespace: social-dev", "community.yaml: |", "Pass: {{ETCD_PASSWORD}}", "image: {{IMAGE}}", "startupProbe:", "failureThreshold: 30", "tcpSocket:", "mountPath: \"/app/apps/api/etc/community.yaml\"", "secretName: come-app-community-api-etcd", "port: 11002", "SPRING_PROFILES_ACTIVE", "value: \"test\"", "SPRING_DATASOURCE_PASSWORD", "secretKeyRef:\n                  name: mysql-auth\n                  key: password", "automountServiceAccountToken: false", "runAsNonRoot: true", "allowPrivilegeEscalation: false", "type: RuntimeDefault"} {
		if !strings.Contains(backend, expected) {
			t.Fatalf("backend manifest missing %q:\n%s", expected, backend)
		}
	}
	if !strings.Contains(backend, "nodeSelector:\n        workload-class: \"application\"") {
		t.Fatalf("backend manifest is not bound to the application node group:\n%s", backend)
	}
	for _, expected := range []string{"kind: Deployment", "kind: Service", "startupProbe:", "failureThreshold: 12", "path: \"/healthz\"", "port: 8080", "runAsNonRoot: true", "allowPrivilegeEscalation: false", "drop:\n                - ALL"} {
		if !strings.Contains(frontend, expected) {
			t.Fatalf("frontend manifest missing %q:\n%s", expected, frontend)
		}
	}
	for _, removed := range []string{"kind: ConfigMap", "configMap:", "kind: ServiceAccount", "serviceAccountName:", "volumeMounts:", "volumes:", "nginx-conf", "mountPath: /etc/nginx/conf.d/default.conf"} {
		if strings.Contains(frontend, removed) {
			t.Fatalf("frontend manifest must load runtime configuration from its image without unrelated identities or volumes, found %q:\n%s", removed, frontend)
		}
	}
	frontendDockerfile := dockerfileContent(delivery.Services[1])
	for _, expected := range []string{"/out/default.conf", "/etc/nginx/conf.d/default.conf", "try_files $uri $uri/ /index.html", "location = /healthz"} {
		if !strings.Contains(frontendDockerfile, expected) {
			t.Fatalf("frontend Dockerfile missing embedded runtime configuration %q:\n%s", expected, frontendDockerfile)
		}
	}
	assertYAMLDocuments(t, backend, 3)
	assertYAMLDocuments(t, frontend, 2)
}

func TestGeneratedJavaManifestRendersCommandAndArgs(t *testing.T) {
	store := newMemoryStore()
	service := newTestService(t, store)
	if _, err := service.SaveServer(context.Background(), "", ServerInput{Key: "main", DisplayName: "GitLab", BaseURL: "https://gitlab.example.com", AccessToken: "token", RootGroup: "ops", Visibility: "private"}); err != nil {
		t.Fatal(err)
	}
	delivery, err := service.SaveDelivery(context.Background(), "java-api", ProjectDelivery{ServerKey: "main", Services: []ServiceSpec{{
		Key: "order-api", WorkloadType: "backend", Language: "java", RuntimeVersion: "21",
		SourceRepository: "https://gitlab.example.com/java/order-api.git", ImageRepository: "registry.example/java/order-api",
		Namespace: "java-prod", ContainerPort: 8080, MemoryRequest: "16Gi", MemoryLimit: "24Gi",
		JavaOptions: []string{" -Dspring.profiles.active={{environment}} ", "-Xms14g", "-Xmx20g", "-jar", "app.jar"},
	}}})
	if err != nil {
		t.Fatal(err)
	}
	if got := delivery.Services[0].JavaOptions[0]; got != "-Dspring.profiles.active={{environment}}" {
		t.Fatalf("Java option was not normalized: %q", got)
	}
	if got := len(delivery.Services[0].JavaOptions); got != 3 {
		t.Fatalf("managed Java launcher arguments were not removed: %#v", delivery.Services[0].JavaOptions)
	}
	manifest := renderManifest("java-api", "prod", delivery.Services[0])
	expectedOrder := []string{
		"          command:\n            - java\n          args:\n",
		`            - -Dspring.profiles.active=prod`,
		`            - -Xms14g`,
		`            - -Xmx20g`,
		`            - -jar`,
		`            - app.jar`,
	}
	position := -1
	for _, expected := range expectedOrder {
		next := strings.Index(manifest[position+1:], expected)
		if next < 0 {
			t.Fatalf("Java manifest missing %q:\n%s", expected, manifest)
		}
		position += next + 1
	}
	if strings.Contains(renderManifest("java-api", "test", delivery.Services[0]), "spring.profiles.active=prod") {
		t.Fatal("environment placeholder was not isolated per generated manifest")
	}
	assertYAMLDocuments(t, manifest, 2)

	legacyService := delivery.Services[0]
	legacyService.JavaOptions = append(legacyService.JavaOptions, "-jar", "app.jar")
	legacyManifest := renderManifest("java-api", "prod", legacyService)
	if got := strings.Count(legacyManifest, "            - -jar\n            - app.jar\n"); got != 1 {
		t.Fatalf("legacy Java launcher arguments were rendered %d times:\n%s", got, legacyManifest)
	}
}

func assertYAMLDocuments(t *testing.T, content string, expected int) {
	t.Helper()
	content = strings.ReplaceAll(content, "{{IMAGE}}", "registry.example/app:v1")
	content = strings.ReplaceAll(content, "{{ETCD_PASSWORD}}", `"redacted"`)
	decoder := yaml.NewDecoder(strings.NewReader(content))
	count := 0
	for {
		var document map[string]any
		err := decoder.Decode(&document)
		if err == io.EOF {
			break
		}
		if err != nil {
			t.Fatalf("generated manifest is invalid YAML: %v\n%s", err, content)
		}
		if len(document) > 0 {
			count++
		}
	}
	if count != expected {
		t.Fatalf("generated manifest contains %d YAML documents, want %d\n%s", count, expected, content)
	}
}

func TestDeliveryValidationRejectsCrossProjectAndUnsafeInputs(t *testing.T) {
	store := newMemoryStore()
	service := newTestService(t, store)
	_, err := service.SaveServer(context.Background(), "", ServerInput{Key: "main", DisplayName: "GitLab", BaseURL: "https://gitlab.example.com", AccessToken: "token", RootGroup: "ops", Visibility: "private"})
	if err != nil {
		t.Fatal(err)
	}
	tests := []ServiceSpec{
		{Key: "gateway", Language: "go", SourceRepository: "https://user:token@gitlab.example.com/game/gateway.git", ImageRepository: "repo/gateway"},
		{Key: "gateway", Language: "go", SourceRepository: "https://gitlab.example.com/game/gateway.git", DockerfileContent: "RUN echo missing-from", ImageRepository: "repo/gateway"},
		{Key: "gateway", Language: "go", SourceRepository: "https://gitlab.example.com/game/gateway.git", BuildContext: `source"; touch unsafe`, ImageRepository: "repo/gateway"},
		{Key: "gateway", Language: "go", SourceRepository: "https://gitlab.example.com/game/gateway.git", ImageRepository: "repo/gateway|unsafe"},
		{Key: "gateway", Language: "python", SourceRepository: "https://gitlab.example.com/game/gateway.git", ImageRepository: "repo/gateway"},
		{Key: "gateway", Language: "go", SourceRepository: "https://gitlab.example.com/game/gateway.git", ImageRepository: "repo/gateway", EnvironmentVariables: map[string]string{"DB_PASSWORD": "must-use-a-secret-reference"}},
		{Key: "gateway", Language: "go", SourceRepository: "https://gitlab.example.com/game/gateway.git", ImageRepository: "repo/gateway", SecretEnvironmentVariables: map[string]SecretKeyReference{"DB_PASSWORD": {SecretName: "invalid/name", SecretKey: "password"}}},
		{Key: "gateway", Language: "go", SourceRepository: "https://gitlab.example.com/game/gateway.git", ImageRepository: "repo/gateway", JavaOptions: []string{"-Xmx2g"}},
		{Key: "gateway", WorkloadType: "backend", Language: "java", SourceRepository: "https://gitlab.example.com/game/gateway.git", ImageRepository: "repo/gateway", JavaOptions: []string{"-jar"}},
		{Key: "gateway", WorkloadType: "backend", Language: "java", SourceRepository: "https://gitlab.example.com/game/gateway.git", ImageRepository: "repo/gateway", JavaOptions: []string{"-Ddb.password=plain-text"}},
		{Key: "gateway", WorkloadType: "backend", Language: "java", SourceRepository: "https://gitlab.example.com/game/gateway.git", ImageRepository: "repo/gateway", JavaOptions: []string{"-Dlabel=value # invalid-yaml-comment"}},
	}
	for _, input := range tests {
		if _, err := service.SaveDelivery(context.Background(), "game-api", ProjectDelivery{ServerKey: "main", Services: []ServiceSpec{input}}); err == nil {
			t.Fatalf("unsafe service was accepted: %#v", input)
		}
	}
	if _, err := service.SaveDelivery(context.Background(), "OTHER_PROJECT", ProjectDelivery{ServerKey: "main"}); err == nil {
		t.Fatal("invalid project scope was accepted")
	}
}

func TestGitLabClientPreservesEscapedNamespace(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.RequestURI != "/api/v4/groups/ops%2Fdelivery" {
			t.Fatalf("unexpected request URI: %s", r.RequestURI)
		}
		if r.Header.Get("PRIVATE-TOKEN") != "token" {
			t.Fatal("GitLab token header is missing")
		}
		_ = json.NewEncoder(w).Encode(gitLabGroup{ID: 1, FullPath: "ops/delivery"})
	}))
	defer server.Close()
	client, err := newGitLabClient(server.URL, "token")
	if err != nil {
		t.Fatal(err)
	}
	group, err := client.group(context.Background(), "ops/delivery")
	if err != nil || group.ID != 1 {
		t.Fatalf("group() = %#v, %v", group, err)
	}
}

func TestProvisionedDeliveryBlocksProjectDeletionUntilDetached(t *testing.T) {
	store := newMemoryStore()
	service := newTestService(t, store)
	store.deliveries["game-api"] = ProjectDelivery{
		ProjectKey: "game-api", ServerKey: "main",
		JenkinsfilesProjectID: 101, JenkinsfilesProjectPath: "ops/game-api-jenkinsfiles", JenkinsfilesCloneURL: "https://gitlab.example.com/ops/game-api-jenkinsfiles.git",
		ManifestsProjectID: 102, ManifestsProjectPath: "ops/game-api-deploy-manifests", ManifestsCloneURL: "https://gitlab.example.com/ops/game-api-deploy-manifests.git",
		Services: []ServiceSpec{{Key: "gateway", Language: "go", SourceRepository: "https://gitlab.example.com/game/gateway.git"}},
	}
	store.repos["game-api/ops-delivery-jenkinsfiles"] = cicd.Repository{Key: "ops-delivery-jenkinsfiles", ProjectKey: "game-api"}
	store.repos["game-api/ops-delivery-manifests"] = cicd.Repository{Key: "ops-delivery-manifests", ProjectKey: "game-api"}
	blocker, err := service.ProjectDeletionBlocker(context.Background(), "game-api")
	if err != nil || blocker == "" {
		t.Fatalf("ProjectDeletionBlocker() = %q, %v", blocker, err)
	}
	if err := service.DetachDelivery(context.Background(), "game-api"); err != nil {
		t.Fatal(err)
	}
	blocker, err = service.ProjectDeletionBlocker(context.Background(), "game-api")
	if err != nil || blocker != "" {
		t.Fatalf("detached blocker = %q, %v", blocker, err)
	}
	detached := store.deliveries["game-api"]
	if detached.ServerKey != "" || detached.JenkinsfilesProjectID != 0 || detached.ManifestsProjectID != 0 {
		t.Fatalf("binding fields were not cleared: %#v", detached)
	}
	if len(detached.Services) != 1 || detached.Services[0].Key != "gateway" {
		t.Fatalf("service catalog was removed during detach: %#v", detached.Services)
	}
	if _, ok := store.repos["game-api/ops-delivery-jenkinsfiles"]; !ok {
		t.Fatal("Jenkinsfile repository registration was removed during detach")
	}
	if _, ok := store.repos["game-api/ops-delivery-manifests"]; !ok {
		t.Fatal("manifest repository registration was removed during detach")
	}
}

func TestProvisionCreatesOneUnifiedRepositoryAndIsIdempotent(t *testing.T) {
	fake := newFakeGitLab(t)
	defer fake.server.Close()
	store := newMemoryStore()
	service := newTestService(t, store)
	_, err := service.SaveServer(context.Background(), "", ServerInput{
		Key: "main", DisplayName: "Local GitLab", BaseURL: fake.server.URL, AccessToken: "token",
		RootGroup: "ops/delivery", DefaultBranch: "main", Visibility: "private", AllowInsecureHTTP: true,
	})
	if err != nil {
		t.Fatal(err)
	}
	_, err = service.SaveDelivery(context.Background(), "game-api", ProjectDelivery{ServerKey: "main", Services: []ServiceSpec{{
		Key: "gateway", Language: "go", SourceRepository: "https://git.example/game/gateway.git", ImageRepository: "registry.example/game/gateway",
	}}})
	if err != nil {
		t.Fatal(err)
	}
	first, err := service.Provision(context.Background(), "game-api")
	if err != nil {
		t.Fatal(err)
	}
	if len(fake.projects) != 1 || len(first.Repositories) != 1 || first.CreatedFiles == 0 || first.UpdatedFiles != 0 {
		t.Fatalf("unexpected first provision: projects=%d result=%#v", len(fake.projects), first)
	}
	if _, ok := store.repos["game-api/ops-delivery-jenkinsfiles"]; !ok {
		t.Fatal("Jenkinsfiles repository was not registered")
	}
	if _, ok := store.repos["game-api/ops-delivery-manifests"]; !ok {
		t.Fatal("manifest repository was not registered")
	}
	if _, ok := store.repos["game-api/ops-delivery"]; !ok {
		t.Fatal("unified delivery repository was not registered")
	}
	delivery := store.deliveries["game-api"]
	delivery.SourceServerKey = "business"
	store.deliveries["game-api"] = delivery
	legacy := legacyKustomizationFiles(delivery)
	fake.files[delivery.ManifestsProjectID][legacy[0].Path] = legacy[0].Content
	fake.files[delivery.ManifestsProjectID][legacy[1].Path] = "resources:\n  - custom-user-overlay.yaml\n"
	second, err := service.Provision(context.Background(), "game-api")
	if err != nil {
		t.Fatal(err)
	}
	if len(fake.projects) != 1 || second.CreatedFiles != 0 || second.UpdatedFiles != 0 || second.DeletedFiles != 1 {
		t.Fatalf("provision was not idempotent: projects=%d result=%#v", len(fake.projects), second)
	}
	if _, exists := fake.files[delivery.ManifestsProjectID][legacy[0].Path]; exists {
		t.Fatal("unchanged platform-generated kustomization was not removed")
	}
	if content := fake.files[delivery.ManifestsProjectID][legacy[1].Path]; content != "resources:\n  - custom-user-overlay.yaml\n" {
		t.Fatalf("user-maintained kustomization was modified: %q", content)
	}
	legacyMetadata := "jobs/game-release/job.yaml"
	fake.files[delivery.JenkinsfilesProjectID][legacyMetadata] = "legacy: true\n"
	_, _, err = service.SyncJobJenkinsfile(context.Background(), "game-api", cicd.Job{
		Key: "game-release", DisplayName: "Game Release", ServiceKeys: []string{"gateway"}, JenkinsfileMode: "generated", ExecutionMode: "serial", FailurePolicy: "stop",
		JenkinsfileCredential: "gitlab", ManifestCredential: "gitlab",
	})
	if err != nil {
		t.Fatal(err)
	}
	if _, exists := fake.files[delivery.JenkinsfilesProjectID][legacyMetadata]; exists {
		t.Fatal("legacy job.yaml was not removed during Jenkinsfile sync")
	}
	if _, exists := fake.files[delivery.JenkinsfilesProjectID]["jobs/game-release/Jenkinsfile"]; !exists {
		t.Fatal("Jenkinsfile was not generated")
	}
	catalog := fake.files[delivery.JenkinsfilesProjectID]["jobs/game-release/services.groovy"]
	if !strings.Contains(catalog, "https://git.example/game/gateway.git") || !strings.Contains(catalog, "ops-game-api-source-read") || strings.Contains(catalog, "/git-relay/") {
		t.Fatalf("generated service catalog did not use the direct source repository and project read credential:\n%s", catalog)
	}
}

func TestActivateAndSafeDeliveryConnectionRebind(t *testing.T) {
	fake := newFakeGitLab(t)
	defer fake.server.Close()
	store := newMemoryStore()
	service := newTestService(t, store)
	for _, key := range []string{"delivery-old", "delivery-new"} {
		if _, err := service.SaveServer(context.Background(), "", ServerInput{
			Key: key, DisplayName: key, BaseURL: fake.server.URL, AccessToken: "token",
			RootGroup: "ops/delivery", DefaultBranch: "main", Visibility: "private", AllowInsecureHTTP: true,
		}); err != nil {
			t.Fatal(err)
		}
	}
	result, err := service.Activate(context.Background(), "game-api", ProjectDelivery{ServerKey: "delivery-old"})
	if err != nil {
		t.Fatal(err)
	}
	if result.Delivery.ProvisionStatus != "ready" || result.Delivery.JenkinsfilesProjectID == 0 || result.Delivery.ManifestsProjectID == 0 {
		t.Fatalf("activate did not return a directly usable binding: %#v", result.Delivery)
	}
	previousJenkinsfilesID := result.Delivery.JenkinsfilesProjectID
	previousManifestsID := result.Delivery.ManifestsProjectID
	rebound, err := service.SaveDelivery(context.Background(), "game-api", ProjectDelivery{ServerKey: "delivery-new"})
	if err != nil {
		t.Fatalf("equivalent delivery connection should be directly reusable: %v", err)
	}
	if rebound.ServerKey != "delivery-new" || rebound.JenkinsfilesProjectID != previousJenkinsfilesID || rebound.ManifestsProjectID != previousManifestsID {
		t.Fatalf("delivery repository identity changed during safe rebind: %#v", rebound)
	}
}

type fakeCredentialSyncer struct {
	items map[string]cicd.Credential
	saved cicd.CredentialInput
}

func (f *fakeCredentialSyncer) ListCredentials(context.Context, string) ([]cicd.Credential, error) {
	items := make([]cicd.Credential, 0, len(f.items))
	for _, item := range f.items {
		items = append(items, item)
	}
	return items, nil
}
func (f *fakeCredentialSyncer) SaveCredential(_ context.Context, project, key string, input cicd.CredentialInput) (cicd.Credential, error) {
	f.saved = input
	item := cicd.Credential{Key: key, ProjectKey: project, ConnectionKey: input.ConnectionKey, DisplayName: input.DisplayName, Kind: input.Kind, ExternalID: input.ExternalID, Description: input.Description, Configured: true}
	f.items[key] = item
	return item, nil
}
func (f *fakeCredentialSyncer) SyncCredential(_ context.Context, _, key string) (cicd.Credential, error) {
	item := f.items[key]
	item.SyncStatus = "ready"
	f.items[key] = item
	return item, nil
}
func (f *fakeCredentialSyncer) ValidateGitCredential(context.Context, string, string, string) (cicd.GitCredentialValidation, error) {
	return cicd.GitCredentialValidation{}, nil
}

func assertGeneratedPath(t *testing.T, files []GeneratedFile, repository, path string) {
	t.Helper()
	for _, file := range files {
		if file.Repository == repository && file.Path == path {
			return
		}
	}
	t.Fatalf("generated file %s/%s was not found", repository, path)
}

func generatedFileContent(t *testing.T, files []GeneratedFile, repository, path string) string {
	t.Helper()
	for _, file := range files {
		if file.Repository == repository && file.Path == path {
			return file.Content
		}
	}
	t.Fatalf("generated file %s/%s was not found", repository, path)
	return ""
}

func newTestService(t *testing.T, store *memoryStore) *Service {
	t.Helper()
	const env = "TEST_GITLAB_CREDENTIAL_KEY"
	t.Setenv(env, base64.StdEncoding.EncodeToString([]byte("0123456789abcdef0123456789abcdef")))
	service, err := New(&appconfig.Config{Security: appconfig.SecurityConfig{CredentialKeyEnv: env}}, store)
	if err != nil {
		t.Fatal(err)
	}
	return service
}

type fakeGitLab struct {
	t        *testing.T
	server   *httptest.Server
	nextID   int64
	projects map[string]gitLabProject
	files    map[int64]map[string]string
}

func newFakeGitLab(t *testing.T) *fakeGitLab {
	fake := &fakeGitLab{t: t, nextID: 100, projects: map[string]gitLabProject{}, files: map[int64]map[string]string{}}
	fake.server = httptest.NewServer(http.HandlerFunc(fake.handle))
	return fake
}

func (f *fakeGitLab) handle(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	if r.Header.Get("PRIVATE-TOKEN") != "token" {
		http.Error(w, `{"message":"unauthorized"}`, http.StatusUnauthorized)
		return
	}
	path := strings.TrimPrefix(r.URL.Path, "/api/v4/")
	switch {
	case r.Method == http.MethodGet && path == "groups/ops/delivery":
		_ = json.NewEncoder(w).Encode(gitLabGroup{ID: 7, FullPath: "ops/delivery"})
	case r.Method == http.MethodPost && path == "projects":
		var input struct {
			Path string `json:"path"`
		}
		if err := json.NewDecoder(r.Body).Decode(&input); err != nil {
			f.t.Error(err)
			http.Error(w, `{}`, 400)
			return
		}
		fullPath := "ops/delivery/" + input.Path
		if _, exists := f.projects[fullPath]; exists {
			http.Error(w, `{"message":"taken"}`, http.StatusBadRequest)
			return
		}
		f.nextID++
		item := gitLabProject{ID: f.nextID, Path: input.Path, PathWithNamespace: fullPath, HTTPURLToRepo: f.server.URL + "/" + fullPath + ".git", DefaultBranch: "main"}
		f.projects[fullPath], f.files[item.ID] = item, map[string]string{}
		w.WriteHeader(http.StatusCreated)
		_ = json.NewEncoder(w).Encode(item)
	case r.Method == http.MethodGet && strings.HasPrefix(path, "projects/") && !strings.Contains(path, "/repository/"):
		fullPath := strings.TrimPrefix(path, "projects/")
		item, exists := f.projects[fullPath]
		if !exists {
			http.Error(w, `{"message":"404 Project Not Found"}`, http.StatusNotFound)
			return
		}
		_ = json.NewEncoder(w).Encode(item)
	case r.Method == http.MethodGet && strings.Contains(path, "/repository/tree"):
		id := fakeProjectID(path)
		if len(f.files[id]) == 0 {
			http.Error(w, `{"message":"404 Tree Not Found"}`, http.StatusNotFound)
			return
		}
		_ = json.NewEncoder(w).Encode([]map[string]any{{"id": "file"}})
	case r.Method == http.MethodGet && strings.Contains(path, "/repository/files/"):
		id := fakeProjectID(path)
		filePath := strings.SplitN(path, "/repository/files/", 2)[1]
		content, exists := f.files[id][filePath]
		if !exists {
			http.Error(w, `{"message":"404 File Not Found"}`, http.StatusNotFound)
			return
		}
		_ = json.NewEncoder(w).Encode(map[string]string{"encoding": "base64", "content": base64.StdEncoding.EncodeToString([]byte(content))})
	case r.Method == http.MethodPost && strings.HasSuffix(path, "/repository/commits"):
		id := fakeProjectID(path)
		var input struct {
			Actions []struct {
				Action   string `json:"action"`
				FilePath string `json:"file_path"`
				Content  string `json:"content"`
			} `json:"actions"`
		}
		if err := json.NewDecoder(r.Body).Decode(&input); err != nil {
			f.t.Error(err)
			http.Error(w, `{}`, 400)
			return
		}
		for _, action := range input.Actions {
			if action.Action == "delete" {
				delete(f.files[id], action.FilePath)
			} else {
				f.files[id][action.FilePath] = action.Content
			}
		}
		w.WriteHeader(http.StatusCreated)
		_, _ = w.Write([]byte(`{}`))
	default:
		f.t.Errorf("unexpected GitLab request: %s %s", r.Method, r.RequestURI)
		http.Error(w, fmt.Sprintf(`{"message":"unexpected %s"}`, r.RequestURI), http.StatusNotFound)
	}
}

func fakeProjectID(path string) int64 {
	value := strings.TrimPrefix(path, "projects/")
	value = strings.SplitN(value, "/", 2)[0]
	id, _ := strconv.ParseInt(value, 10, 64)
	return id
}

type memoryStore struct {
	servers    map[string]StoredServer
	deliveries map[string]ProjectDelivery
	repos      map[string]cicd.Repository
}

func newMemoryStore() *memoryStore {
	return &memoryStore{servers: map[string]StoredServer{}, deliveries: map[string]ProjectDelivery{}, repos: map[string]cicd.Repository{}}
}

func (m *memoryStore) ListGitLabServers(context.Context) ([]StoredServer, error) {
	items := []StoredServer{}
	for _, item := range m.servers {
		items = append(items, item)
	}
	return items, nil
}
func (m *memoryStore) GetGitLabServer(_ context.Context, key string) (StoredServer, error) {
	item, ok := m.servers[key]
	if !ok {
		return item, os.ErrNotExist
	}
	return item, nil
}
func (m *memoryStore) SaveGitLabServer(_ context.Context, item StoredServer) error {
	now := time.Now().UTC()
	if item.CreatedAt.IsZero() {
		item.CreatedAt = now
	}
	item.UpdatedAt = now
	m.servers[item.Key] = item
	return nil
}
func (m *memoryStore) DeleteGitLabServer(_ context.Context, key string) error {
	delete(m.servers, key)
	return nil
}
func (m *memoryStore) GitLabServerBindingCount(_ context.Context, key string) (int, error) {
	count := 0
	for _, item := range m.deliveries {
		if item.ServerKey == key || item.SourceServerKey == key {
			count++
		}
	}
	return count, nil
}
func (m *memoryStore) GitLabServerBindingRootGroups(_ context.Context, key string) ([]string, error) {
	groups := []string{}
	seen := map[string]bool{}
	for _, item := range m.deliveries {
		for _, binding := range []struct{ server, group string }{{item.ServerKey, item.RootGroup}, {item.SourceServerKey, item.SourceRootGroup}} {
			if binding.server == key && binding.group != "" && !seen[strings.ToLower(binding.group)] {
				seen[strings.ToLower(binding.group)] = true
				groups = append(groups, binding.group)
			}
		}
	}
	return groups, nil
}
func (m *memoryStore) GitLabServerSourceRepositories(_ context.Context, key string) ([]string, error) {
	result := []string{}
	for _, item := range m.deliveries {
		if item.SourceServerKey != key {
			continue
		}
		for _, service := range item.Services {
			if service.SourceRepository != "" {
				result = append(result, service.SourceRepository)
			}
		}
	}
	return result, nil
}
func (m *memoryStore) GetProjectGitLabDelivery(_ context.Context, project string) (ProjectDelivery, error) {
	item, ok := m.deliveries[project]
	if !ok {
		return item, os.ErrNotExist
	}
	return item, nil
}
func (m *memoryStore) SaveProjectGitLabDelivery(_ context.Context, item ProjectDelivery) error {
	now := time.Now().UTC()
	if item.CreatedAt.IsZero() {
		item.CreatedAt = now
	}
	item.UpdatedAt = now
	m.deliveries[item.ProjectKey] = item
	return nil
}
func (m *memoryStore) DetachProjectGitLabDelivery(_ context.Context, project string) error {
	item, ok := m.deliveries[project]
	if !ok {
		return os.ErrNotExist
	}
	item.ServerKey = ""
	item.RootGroup = ""
	item.SourceServerKey = ""
	item.SourceRootGroup = ""
	item.JenkinsfilesProjectID = 0
	item.JenkinsfilesProjectPath = ""
	item.JenkinsfilesCloneURL = ""
	item.ManifestsProjectID = 0
	item.ManifestsProjectPath = ""
	item.ManifestsCloneURL = ""
	item.ProvisionStatus = ""
	item.ProvisionError = ""
	item.LastProvisionedAt = time.Time{}
	m.deliveries[project] = item
	return nil
}
func (m *memoryStore) GetCICDRepository(_ context.Context, project, key string) (cicd.Repository, error) {
	item, ok := m.repos[project+"/"+key]
	if !ok {
		return item, os.ErrNotExist
	}
	return item, nil
}
func (m *memoryStore) SaveCICDRepository(_ context.Context, item cicd.Repository) error {
	m.repos[item.ProjectKey+"/"+item.Key] = item
	return nil
}
